### ISSUE TITLE
Refactor compare_sorucelists.py

### ISSUE THREAD

**Issue by dulude** [spacetelescope/drizzlepac#556]
**TODOs**
- [x] Convert X and Y difference values into arcsec based on instrument-specific platescale value
- [x]  RA and Dec differences
     - [x] compute RA and Dec differences properly using [astropy.skycoordinates](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html); compute combined RA/Dec angular separation differences instead of differences of individual RA and Dec components.
     - [x] Figure out why I'm getting wildly incorrect values when converting HLA classic RA, Dec values with read_hla_sourcelists.py
- [ ] Have two test criteria for linear comparisons: 
     - [x] <=95% of the differences must be within 3 sigma of the clipped mean
     - [x] column-specific maximum allowable mean differences (this will depend on the column -- x, y, ra and dec could be max mean difference of 0.1 arcsec for example, magnitudes would have a different max mean difference, etc.)
     - [x] create dictionary of max_diff values for all columns
     - [ ] Verify max_diff_dict values for _x, y, ra, dec,_ and _flag_
     - [ ] replace max_diff_dict placeholder values with actual values for _flux_inner, flux_outer, mag_inner, mag_outer, mag_inner_error, mag_outer_error, msky, stdev,_ and _ci_
- [ ] Compute Magnitude differences properly (See [astropy.units)](https://docs.astropy.org/en/stable/units/#)
- [x] wholesale-ignore all values in a given line across all columns from both lists if any value in said line contains a missing, np.inf, or np.nan value
- [x] Add flag-value based rejection (good flag bits = 0, 1, and/or 4, ignore lines containing flag bits other than these). This could also be an optional user-specified input.
- [x] Add correct units to X axis titles of plots generated by computeLinearStats().
- [x] As per @mackjenn's suggestion, add mag vs. delta mag plots

**Comment by dulude** [comment]
see branch [compare_sourcelists_refactor](https://github.com/dulude/drizzlepac/tree/compare_sourcelists_refactor).

**Comment by dulude** [comment]
Pushing what I've got so far now that the HLA RA/DEC conversion bug is fixed. Will circle back to the remaining issues at a later time.

**Comment by mackjenn** [comment]
@dulude  When you say 'dmag vs mag plots', do you mean dmag(HLA-HAP)?
It would also be useful to see mag_error vs mag, with HLA and HAP overplotted in different colors.

**Comment by stsci-hack** [comment]
Resolved with #517 (on 27-Jan-2020).
